name: admin_web_panel
description: "Panel de administración para El Gran Molino"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase - Versiones compatibles (importantes)
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4

  firebase_storage: ^12.3.4
  image_picker: ^1.1.2

  
  # Formateo de fechas
  intl: ^0.19.0
  
  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true